pyrofork: fix search_message
* TypeError: Search.__init__() got an unexpected keyword argument 'thread_id'

Signed-off-by: wulan17 <wulan17@nusantararom.org>
(cherry picked from commit 1bcf2f7be6ba68d612647d09e34f64f5c05d8361)